git clone https://github.com/ilikenwf/DarkAgent
git clone https://github.com/werkamsus/Lilith
git clone https://github.com/0xIslamTaha/Python-Rootkit
git clone https://github.com/wandering-nomad/Spidernet
git clone https://github.com/fadinglr/Parat
git clone https://github.com/mehulj94/BrainDamage
git clone https://github.com/Vigorian/uRAT
git clone https://github.com/erikbarzdukas/CrunchRAT
git clone https://github.com/canselcik/Epicenter-Remote-Administration-Tool
git clone https://github.com/JershDervis/MonitorJ-RAT
git clone https://github.com/globalpolicy/PhoneMonitor
git clone https://github.com/AdvancedHacker101/C-Sharp-R.A.T-Server
git clone https://github.com/R-Smith/Splice-Admin
git clone https://github.com/NYAN-x-CAT/AsyncRAT
git clone https://github.com/c4wrd/LaRat
git clone https://github.com/valsov/BackNet
git clone https://github.com/Swordf1sh/Moderat
git clone https://github.com/0blio/caesarRAT
git clone https://github.com/devqore/myrdp
git clone https://github.com/davidtavarez/pinky
git clone https://github.com/mwesto/nodeRat.Io
git clone https://github.com/b7bassam/Torch
