# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hostconfig.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HostConfig(object):
    def setupUi(self, HostConfig):
        HostConfig.setObjectName(_fromUtf8("HostConfig"))
        HostConfig.resize(358, 282)
        HostConfig.setMaximumSize(QtCore.QSize(358, 282))
        self.verticalLayout = QtGui.QVBoxLayout(HostConfig)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nameLabel = QtGui.QLabel(HostConfig)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.name = QtGui.QLineEdit(HostConfig)
        self.name.setAutoFillBackground(False)
        self.name.setText(_fromUtf8(""))
        self.name.setPlaceholderText(_fromUtf8(""))
        self.name.setObjectName(_fromUtf8("name"))
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.hostLabel = QtGui.QLabel(HostConfig)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hostLabel.setFont(font)
        self.hostLabel.setObjectName(_fromUtf8("hostLabel"))
        self.gridLayout.addWidget(self.hostLabel, 1, 0, 1, 1)
        self.address = QtGui.QLineEdit(HostConfig)
        self.address.setPlaceholderText(_fromUtf8(""))
        self.address.setObjectName(_fromUtf8("address"))
        self.gridLayout.addWidget(self.address, 1, 1, 1, 1)
        self.userLabel = QtGui.QLabel(HostConfig)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.userLabel.setFont(font)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.gridLayout.addWidget(self.userLabel, 2, 0, 1, 1)
        self.user = QtGui.QLineEdit(HostConfig)
        self.user.setPlaceholderText(_fromUtf8(""))
        self.user.setObjectName(_fromUtf8("user"))
        self.gridLayout.addWidget(self.user, 2, 1, 1, 1)
        self.passwordLabel = QtGui.QLabel(HostConfig)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.gridLayout.addWidget(self.passwordLabel, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.password = QtGui.QLineEdit(HostConfig)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setPlaceholderText(_fromUtf8(""))
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_2.addWidget(self.password)
        self.showPassword = QtGui.QPushButton(HostConfig)
        self.showPassword.setMaximumSize(QtCore.QSize(30, 26))
        self.showPassword.setFocusPolicy(QtCore.Qt.NoFocus)
        self.showPassword.setToolTip(_fromUtf8("Show password"))
        self.showPassword.setAccessibleName(_fromUtf8(""))
        self.showPassword.setAccessibleDescription(_fromUtf8(""))
        self.showPassword.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ico/eye.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showPassword.setIcon(icon)
        self.showPassword.setIconSize(QtCore.QSize(30, 20))
        self.showPassword.setCheckable(True)
        self.showPassword.setFlat(True)
        self.showPassword.setObjectName(_fromUtf8("showPassword"))
        self.horizontalLayout_2.addWidget(self.showPassword)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.groupLabel = QtGui.QLabel(HostConfig)
        self.groupLabel.setObjectName(_fromUtf8("groupLabel"))
        self.gridLayout.addWidget(self.groupLabel, 4, 0, 1, 1)
        self.group = QtGui.QComboBox(HostConfig)
        self.group.setStatusTip(_fromUtf8(""))
        self.group.setAccessibleName(_fromUtf8(""))
        self.group.setAccessibleDescription(_fromUtf8(""))
        self.group.setInputMethodHints(QtCore.Qt.ImhNone)
        self.group.setEditable(True)
        self.group.setMaxVisibleItems(100)
        self.group.setFrame(True)
        self.group.setObjectName(_fromUtf8("group"))
        self.gridLayout.addWidget(self.group, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.informationLabel = QtGui.QLabel(HostConfig)
        self.informationLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.informationLabel.setFont(font)
        self.informationLabel.setStyleSheet(_fromUtf8("color: red"))
        self.informationLabel.setText(_fromUtf8(""))
        self.informationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.informationLabel.setWordWrap(False)
        self.informationLabel.setObjectName(_fromUtf8("informationLabel"))
        self.verticalLayout.addWidget(self.informationLabel)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.connectCheckBox = QtGui.QCheckBox(HostConfig)
        self.connectCheckBox.setEnabled(True)
        self.connectCheckBox.setChecked(True)
        self.connectCheckBox.setObjectName(_fromUtf8("connectCheckBox"))
        self.horizontalLayout.addWidget(self.connectCheckBox)
        self.buttonBox = QtGui.QDialogButtonBox(HostConfig)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(HostConfig)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), HostConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(HostConfig)

    def retranslateUi(self, HostConfig):
        HostConfig.setWindowTitle(_translate("HostConfig", "Host config", None))
        self.nameLabel.setText(_translate("HostConfig", "Name:", None))
        self.hostLabel.setText(_translate("HostConfig", "Host:", None))
        self.userLabel.setText(_translate("HostConfig", "User:", None))
        self.passwordLabel.setText(_translate("HostConfig", "Password:", None))
        self.groupLabel.setText(_translate("HostConfig", "Group:", None))
        self.connectCheckBox.setText(_translate("HostConfig", "connect", None))

import resources_rc
