# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(868, 454)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.clientsTabs = QtGui.QTabWidget(self.centralwidget)
        self.clientsTabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clientsTabs.setIconSize(QtCore.QSize(18, 18))
        self.clientsTabs.setDocumentMode(False)
        self.clientsTabs.setTabsClosable(False)
        self.clientsTabs.setMovable(False)
        self.clientsTabs.setObjectName(_fromUtf8("clientsTabs"))
        self.onlineClientsTab = QtGui.QWidget()
        self.onlineClientsTab.setObjectName(_fromUtf8("onlineClientsTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.onlineClientsTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.viewLogsButton = QtGui.QPushButton(self.onlineClientsTab)
        self.viewLogsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.viewLogsButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/log_viewer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewLogsButton.setIcon(icon1)
        self.viewLogsButton.setIconSize(QtCore.QSize(16, 16))
        self.viewLogsButton.setObjectName(_fromUtf8("viewLogsButton"))
        self.horizontalLayout_6.addWidget(self.viewLogsButton)
        self.noteButton = QtGui.QPushButton(self.onlineClientsTab)
        self.noteButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/note.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noteButton.setIcon(icon2)
        self.noteButton.setObjectName(_fromUtf8("noteButton"))
        self.horizontalLayout_6.addWidget(self.noteButton)
        self.logSettingsButton = QtGui.QPushButton(self.onlineClientsTab)
        self.logSettingsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.logSettingsButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/other_settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logSettingsButton.setIcon(icon3)
        self.logSettingsButton.setIconSize(QtCore.QSize(16, 16))
        self.logSettingsButton.setObjectName(_fromUtf8("logSettingsButton"))
        self.horizontalLayout_6.addWidget(self.logSettingsButton)
        self.line_2 = QtGui.QFrame(self.onlineClientsTab)
        self.line_2.setMinimumSize(QtCore.QSize(20, 0))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_6.addWidget(self.line_2)
        self.setAliasButton = QtGui.QPushButton(self.onlineClientsTab)
        self.setAliasButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setAliasButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/set_alias.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setAliasButton.setIcon(icon4)
        self.setAliasButton.setIconSize(QtCore.QSize(16, 16))
        self.setAliasButton.setObjectName(_fromUtf8("setAliasButton"))
        self.horizontalLayout_6.addWidget(self.setAliasButton)
        self.updateSourceButton = QtGui.QPushButton(self.onlineClientsTab)
        self.updateSourceButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.updateSourceButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/update_source.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateSourceButton.setIcon(icon5)
        self.updateSourceButton.setIconSize(QtCore.QSize(16, 16))
        self.updateSourceButton.setObjectName(_fromUtf8("updateSourceButton"))
        self.horizontalLayout_6.addWidget(self.updateSourceButton)
        self.line = QtGui.QFrame(self.onlineClientsTab)
        self.line.setMinimumSize(QtCore.QSize(20, 0))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_6.addWidget(self.line)
        self.shellButton = QtGui.QPushButton(self.onlineClientsTab)
        self.shellButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shellButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/remote_shell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shellButton.setIcon(icon6)
        self.shellButton.setIconSize(QtCore.QSize(16, 16))
        self.shellButton.setObjectName(_fromUtf8("shellButton"))
        self.horizontalLayout_6.addWidget(self.shellButton)
        self.explorerButton = QtGui.QPushButton(self.onlineClientsTab)
        self.explorerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.explorerButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/remote_explorer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.explorerButton.setIcon(icon7)
        self.explorerButton.setIconSize(QtCore.QSize(16, 16))
        self.explorerButton.setObjectName(_fromUtf8("explorerButton"))
        self.horizontalLayout_6.addWidget(self.explorerButton)
        self.scriptingButton = QtGui.QPushButton(self.onlineClientsTab)
        self.scriptingButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scriptingButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/remote_scripting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scriptingButton.setIcon(icon8)
        self.scriptingButton.setIconSize(QtCore.QSize(16, 16))
        self.scriptingButton.setObjectName(_fromUtf8("scriptingButton"))
        self.horizontalLayout_6.addWidget(self.scriptingButton)
        self.screenshotButton = QtGui.QPushButton(self.onlineClientsTab)
        self.screenshotButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.screenshotButton.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/desktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon9)
        self.screenshotButton.setIconSize(QtCore.QSize(16, 16))
        self.screenshotButton.setObjectName(_fromUtf8("screenshotButton"))
        self.horizontalLayout_6.addWidget(self.screenshotButton)
        self.webcamButton = QtGui.QPushButton(self.onlineClientsTab)
        self.webcamButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.webcamButton.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/webcam.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webcamButton.setIcon(icon10)
        self.webcamButton.setIconSize(QtCore.QSize(16, 16))
        self.webcamButton.setObjectName(_fromUtf8("webcamButton"))
        self.horizontalLayout_6.addWidget(self.webcamButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.clientsTable = QtGui.QTableWidget(self.onlineClientsTab)
        self.clientsTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clientsTable.setAutoFillBackground(False)
        self.clientsTable.setFrameShadow(QtGui.QFrame.Plain)
        self.clientsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.clientsTable.setDragDropOverwriteMode(False)
        self.clientsTable.setAlternatingRowColors(False)
        self.clientsTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.clientsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.clientsTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.clientsTable.setShowGrid(False)
        self.clientsTable.setGridStyle(QtCore.Qt.NoPen)
        self.clientsTable.setWordWrap(False)
        self.clientsTable.setCornerButtonEnabled(False)
        self.clientsTable.setObjectName(_fromUtf8("clientsTable"))
        self.clientsTable.setColumnCount(5)
        self.clientsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.clientsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.clientsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.clientsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.clientsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.clientsTable.setHorizontalHeaderItem(4, item)
        self.clientsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.clientsTable.horizontalHeader().setDefaultSectionSize(100)
        self.clientsTable.horizontalHeader().setSortIndicatorShown(False)
        self.clientsTable.horizontalHeader().setStretchLastSection(True)
        self.clientsTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.clientsTable)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.clientsTabs.addTab(self.onlineClientsTab, _fromUtf8(""))
        self.directTab = QtGui.QWidget()
        self.directTab.setObjectName(_fromUtf8("directTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.directTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.directShellButton = QtGui.QPushButton(self.directTab)
        self.directShellButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.directShellButton.setStyleSheet(_fromUtf8("1"))
        self.directShellButton.setText(_fromUtf8(""))
        self.directShellButton.setIcon(icon6)
        self.directShellButton.setIconSize(QtCore.QSize(16, 16))
        self.directShellButton.setObjectName(_fromUtf8("directShellButton"))
        self.horizontalLayout_9.addWidget(self.directShellButton)
        self.directExplorerButton = QtGui.QPushButton(self.directTab)
        self.directExplorerButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.directExplorerButton.setStyleSheet(_fromUtf8("1"))
        self.directExplorerButton.setText(_fromUtf8(""))
        self.directExplorerButton.setIcon(icon7)
        self.directExplorerButton.setIconSize(QtCore.QSize(16, 16))
        self.directExplorerButton.setObjectName(_fromUtf8("directExplorerButton"))
        self.horizontalLayout_9.addWidget(self.directExplorerButton)
        self.directScriptingButton = QtGui.QPushButton(self.directTab)
        self.directScriptingButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.directScriptingButton.setStyleSheet(_fromUtf8("1"))
        self.directScriptingButton.setText(_fromUtf8(""))
        self.directScriptingButton.setIcon(icon8)
        self.directScriptingButton.setIconSize(QtCore.QSize(16, 16))
        self.directScriptingButton.setObjectName(_fromUtf8("directScriptingButton"))
        self.horizontalLayout_9.addWidget(self.directScriptingButton)
        self.directScreenshotButton = QtGui.QPushButton(self.directTab)
        self.directScreenshotButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.directScreenshotButton.setStyleSheet(_fromUtf8("1"))
        self.directScreenshotButton.setText(_fromUtf8(""))
        self.directScreenshotButton.setIcon(icon9)
        self.directScreenshotButton.setIconSize(QtCore.QSize(16, 16))
        self.directScreenshotButton.setObjectName(_fromUtf8("directScreenshotButton"))
        self.horizontalLayout_9.addWidget(self.directScreenshotButton)
        self.directWebcamButton = QtGui.QPushButton(self.directTab)
        self.directWebcamButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.directWebcamButton.setStyleSheet(_fromUtf8("1"))
        self.directWebcamButton.setText(_fromUtf8(""))
        self.directWebcamButton.setIcon(icon10)
        self.directWebcamButton.setIconSize(QtCore.QSize(16, 16))
        self.directWebcamButton.setObjectName(_fromUtf8("directWebcamButton"))
        self.horizontalLayout_9.addWidget(self.directWebcamButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.directClientsTable = QtGui.QTableWidget(self.directTab)
        self.directClientsTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.directClientsTable.setAutoFillBackground(False)
        self.directClientsTable.setStyleSheet(_fromUtf8("1"))
        self.directClientsTable.setFrameShadow(QtGui.QFrame.Plain)
        self.directClientsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.directClientsTable.setDragDropOverwriteMode(False)
        self.directClientsTable.setAlternatingRowColors(False)
        self.directClientsTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.directClientsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.directClientsTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.directClientsTable.setShowGrid(False)
        self.directClientsTable.setGridStyle(QtCore.Qt.NoPen)
        self.directClientsTable.setWordWrap(False)
        self.directClientsTable.setCornerButtonEnabled(False)
        self.directClientsTable.setObjectName(_fromUtf8("directClientsTable"))
        self.directClientsTable.setColumnCount(3)
        self.directClientsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.directClientsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.directClientsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.directClientsTable.setHorizontalHeaderItem(2, item)
        self.directClientsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.directClientsTable.horizontalHeader().setDefaultSectionSize(100)
        self.directClientsTable.horizontalHeader().setSortIndicatorShown(False)
        self.directClientsTable.horizontalHeader().setStretchLastSection(True)
        self.directClientsTable.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.directClientsTable)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.clientsTabs.addTab(self.directTab, _fromUtf8(""))
        self.offlineClientsTab = QtGui.QWidget()
        self.offlineClientsTab.setObjectName(_fromUtf8("offlineClientsTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.offlineClientsTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.viewOfflineLogsButton = QtGui.QPushButton(self.offlineClientsTab)
        self.viewOfflineLogsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.viewOfflineLogsButton.setStyleSheet(_fromUtf8("1"))
        self.viewOfflineLogsButton.setText(_fromUtf8(""))
        self.viewOfflineLogsButton.setIcon(icon1)
        self.viewOfflineLogsButton.setIconSize(QtCore.QSize(16, 16))
        self.viewOfflineLogsButton.setObjectName(_fromUtf8("viewOfflineLogsButton"))
        self.horizontalLayout_7.addWidget(self.viewOfflineLogsButton)
        self.setOfflineAliasButton = QtGui.QPushButton(self.offlineClientsTab)
        self.setOfflineAliasButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setOfflineAliasButton.setStyleSheet(_fromUtf8("1"))
        self.setOfflineAliasButton.setText(_fromUtf8(""))
        self.setOfflineAliasButton.setIcon(icon4)
        self.setOfflineAliasButton.setIconSize(QtCore.QSize(16, 16))
        self.setOfflineAliasButton.setObjectName(_fromUtf8("setOfflineAliasButton"))
        self.horizontalLayout_7.addWidget(self.setOfflineAliasButton)
        self.removeClientButton = QtGui.QPushButton(self.offlineClientsTab)
        self.removeClientButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.removeClientButton.setStyleSheet(_fromUtf8("1"))
        self.removeClientButton.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeClientButton.setIcon(icon11)
        self.removeClientButton.setIconSize(QtCore.QSize(16, 16))
        self.removeClientButton.setObjectName(_fromUtf8("removeClientButton"))
        self.horizontalLayout_7.addWidget(self.removeClientButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.offlineClientsTable = QtGui.QTableWidget(self.offlineClientsTab)
        self.offlineClientsTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.offlineClientsTable.setAutoFillBackground(False)
        self.offlineClientsTable.setStyleSheet(_fromUtf8("1"))
        self.offlineClientsTable.setFrameShadow(QtGui.QFrame.Plain)
        self.offlineClientsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.offlineClientsTable.setDragDropOverwriteMode(False)
        self.offlineClientsTable.setAlternatingRowColors(False)
        self.offlineClientsTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.offlineClientsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.offlineClientsTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.offlineClientsTable.setShowGrid(False)
        self.offlineClientsTable.setGridStyle(QtCore.Qt.NoPen)
        self.offlineClientsTable.setWordWrap(False)
        self.offlineClientsTable.setCornerButtonEnabled(False)
        self.offlineClientsTable.setObjectName(_fromUtf8("offlineClientsTable"))
        self.offlineClientsTable.setColumnCount(5)
        self.offlineClientsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.offlineClientsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.offlineClientsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.offlineClientsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.offlineClientsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.offlineClientsTable.setHorizontalHeaderItem(4, item)
        self.offlineClientsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.offlineClientsTable.horizontalHeader().setDefaultSectionSize(100)
        self.offlineClientsTable.horizontalHeader().setSortIndicatorShown(False)
        self.offlineClientsTable.horizontalHeader().setStretchLastSection(True)
        self.offlineClientsTable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.offlineClientsTable)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.clientsTabs.addTab(self.offlineClientsTab, _fromUtf8(""))
        self.moderatorsTab = QtGui.QWidget()
        self.moderatorsTab.setObjectName(_fromUtf8("moderatorsTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.moderatorsTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.addModeratorButton = QtGui.QPushButton(self.moderatorsTab)
        self.addModeratorButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addModeratorButton.setStyleSheet(_fromUtf8("1"))
        self.addModeratorButton.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/add_moderator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addModeratorButton.setIcon(icon12)
        self.addModeratorButton.setIconSize(QtCore.QSize(16, 16))
        self.addModeratorButton.setObjectName(_fromUtf8("addModeratorButton"))
        self.horizontalLayout_8.addWidget(self.addModeratorButton)
        self.changePasswordButton = QtGui.QPushButton(self.moderatorsTab)
        self.changePasswordButton.setStyleSheet(_fromUtf8("1"))
        self.changePasswordButton.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/password.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.changePasswordButton.setIcon(icon13)
        self.changePasswordButton.setIconSize(QtCore.QSize(16, 16))
        self.changePasswordButton.setObjectName(_fromUtf8("changePasswordButton"))
        self.horizontalLayout_8.addWidget(self.changePasswordButton)
        self.changePrivilegesButton = QtGui.QPushButton(self.moderatorsTab)
        self.changePrivilegesButton.setStyleSheet(_fromUtf8("1"))
        self.changePrivilegesButton.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/privileges.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.changePrivilegesButton.setIcon(icon14)
        self.changePrivilegesButton.setIconSize(QtCore.QSize(16, 16))
        self.changePrivilegesButton.setObjectName(_fromUtf8("changePrivilegesButton"))
        self.horizontalLayout_8.addWidget(self.changePrivilegesButton)
        self.removeModeratorButton = QtGui.QPushButton(self.moderatorsTab)
        self.removeModeratorButton.setStyleSheet(_fromUtf8("1"))
        self.removeModeratorButton.setText(_fromUtf8(""))
        self.removeModeratorButton.setIcon(icon11)
        self.removeModeratorButton.setIconSize(QtCore.QSize(16, 16))
        self.removeModeratorButton.setObjectName(_fromUtf8("removeModeratorButton"))
        self.horizontalLayout_8.addWidget(self.removeModeratorButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.moderatorsTable = QtGui.QTableWidget(self.moderatorsTab)
        self.moderatorsTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.moderatorsTable.setAutoFillBackground(False)
        self.moderatorsTable.setStyleSheet(_fromUtf8("1"))
        self.moderatorsTable.setFrameShadow(QtGui.QFrame.Plain)
        self.moderatorsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.moderatorsTable.setDragDropOverwriteMode(False)
        self.moderatorsTable.setAlternatingRowColors(False)
        self.moderatorsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.moderatorsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.moderatorsTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.moderatorsTable.setShowGrid(False)
        self.moderatorsTable.setGridStyle(QtCore.Qt.NoPen)
        self.moderatorsTable.setWordWrap(False)
        self.moderatorsTable.setCornerButtonEnabled(False)
        self.moderatorsTable.setObjectName(_fromUtf8("moderatorsTable"))
        self.moderatorsTable.setColumnCount(6)
        self.moderatorsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.moderatorsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.moderatorsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.moderatorsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.moderatorsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.moderatorsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.moderatorsTable.setHorizontalHeaderItem(5, item)
        self.moderatorsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.moderatorsTable.horizontalHeader().setDefaultSectionSize(100)
        self.moderatorsTable.horizontalHeader().setSortIndicatorShown(False)
        self.moderatorsTable.horizontalHeader().setStretchLastSection(True)
        self.moderatorsTable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.moderatorsTable)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.onlineClientsCountLabel = QtGui.QLabel(self.moderatorsTab)
        self.onlineClientsCountLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.onlineClientsCountLabel.setStyleSheet(_fromUtf8("1"))
        self.onlineClientsCountLabel.setObjectName(_fromUtf8("onlineClientsCountLabel"))
        self.horizontalLayout_2.addWidget(self.onlineClientsCountLabel)
        self.allClientsProgress = QtGui.QProgressBar(self.moderatorsTab)
        self.allClientsProgress.setMaximumSize(QtCore.QSize(16777215, 8))
        self.allClientsProgress.setStyleSheet(_fromUtf8("1"))
        self.allClientsProgress.setProperty("value", 35)
        self.allClientsProgress.setTextVisible(False)
        self.allClientsProgress.setObjectName(_fromUtf8("allClientsProgress"))
        self.horizontalLayout_2.addWidget(self.allClientsProgress)
        self.offlineClientsCountLabel = QtGui.QLabel(self.moderatorsTab)
        self.offlineClientsCountLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.offlineClientsCountLabel.setStyleSheet(_fromUtf8("1"))
        self.offlineClientsCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offlineClientsCountLabel.setObjectName(_fromUtf8("offlineClientsCountLabel"))
        self.horizontalLayout_2.addWidget(self.offlineClientsCountLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.clientsTabs.addTab(self.moderatorsTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.clientsTabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuRemote_Server = QtGui.QMenu(self.menubar)
        self.menuRemote_Server.setObjectName(_fromUtf8("menuRemote_Server"))
        self.menuLocal_Server = QtGui.QMenu(self.menubar)
        self.menuLocal_Server.setObjectName(_fromUtf8("menuLocal_Server"))
        self.menuFilter = QtGui.QMenu(self.menubar)
        self.menuFilter.setObjectName(_fromUtf8("menuFilter"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.actionStartListen_for_connections = QtGui.QAction(MainWindow)
        self.actionStartListen_for_connections.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartListen_for_connections.setIcon(icon15)
        self.actionStartListen_for_connections.setObjectName(_fromUtf8("actionStartListen_for_connections"))
        self.actionStopListen_for_connections = QtGui.QAction(MainWindow)
        self.actionStopListen_for_connections.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/disconnect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopListen_for_connections.setIcon(icon16)
        self.actionStopListen_for_connections.setObjectName(_fromUtf8("actionStopListen_for_connections"))
        self.actionViewer_Configuration = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewer_Configuration.setIcon(icon17)
        self.actionViewer_Configuration.setObjectName(_fromUtf8("actionViewer_Configuration"))
        self.actionRemote_Shell = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/mshell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemote_Shell.setIcon(icon18)
        self.actionRemote_Shell.setObjectName(_fromUtf8("actionRemote_Shell"))
        self.actionRemote_Explorer = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/mexplorer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemote_Explorer.setIcon(icon19)
        self.actionRemote_Explorer.setObjectName(_fromUtf8("actionRemote_Explorer"))
        self.actionRemote_Process_Manager = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/mprocesses.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemote_Process_Manager.setIcon(icon20)
        self.actionRemote_Process_Manager.setObjectName(_fromUtf8("actionRemote_Process_Manager"))
        self.actionRemote_Microphone = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/maudio.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemote_Microphone.setIcon(icon21)
        self.actionRemote_Microphone.setObjectName(_fromUtf8("actionRemote_Microphone"))
        self.actionRemote_Scripting = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/script.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemote_Scripting.setIcon(icon22)
        self.actionRemote_Scripting.setObjectName(_fromUtf8("actionRemote_Scripting"))
        self.actionRemote_Keylogger = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/mkeylogger.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemote_Keylogger.setIcon(icon23)
        self.actionRemote_Keylogger.setObjectName(_fromUtf8("actionRemote_Keylogger"))
        self.actionDesktop_Preview = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/mdesktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDesktop_Preview.setIcon(icon24)
        self.actionDesktop_Preview.setObjectName(_fromUtf8("actionDesktop_Preview"))
        self.actionWebcam_Preview = QtGui.QAction(MainWindow)
        self.actionWebcam_Preview.setIcon(icon10)
        self.actionWebcam_Preview.setObjectName(_fromUtf8("actionWebcam_Preview"))
        self.actionStop_Client = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/terminate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_Client.setIcon(icon25)
        self.actionStop_Client.setObjectName(_fromUtf8("actionStop_Client"))
        self.actionLock_Client = QtGui.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/lock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLock_Client.setIcon(icon26)
        self.actionLock_Client.setObjectName(_fromUtf8("actionLock_Client"))
        self.actionLog_off = QtGui.QAction(MainWindow)
        self.actionLog_off.setObjectName(_fromUtf8("actionLog_off"))
        self.actionReboot = QtGui.QAction(MainWindow)
        self.actionReboot.setObjectName(_fromUtf8("actionReboot"))
        self.actionShutdown = QtGui.QAction(MainWindow)
        self.actionShutdown.setObjectName(_fromUtf8("actionShutdown"))
        self.actionUnlock_Client = QtGui.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/unlock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnlock_Client.setIcon(icon27)
        self.actionUnlock_Client.setObjectName(_fromUtf8("actionUnlock_Client"))
        self.actionSet_Alias = QtGui.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/add_alias.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Alias.setIcon(icon28)
        self.actionSet_Alias.setObjectName(_fromUtf8("actionSet_Alias"))
        self.actionRun_As_Admin = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/run_as_admin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun_As_Admin.setIcon(icon29)
        self.actionRun_As_Admin.setObjectName(_fromUtf8("actionRun_As_Admin"))
        self.actionTerminate_Client = QtGui.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTerminate_Client.setIcon(icon30)
        self.actionTerminate_Client.setObjectName(_fromUtf8("actionTerminate_Client"))
        self.actionWindows_Client_PyInstaller = QtGui.QAction(MainWindow)
        self.actionWindows_Client_PyInstaller.setObjectName(_fromUtf8("actionWindows_Client_PyInstaller"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionStartServer = QtGui.QAction(MainWindow)
        self.actionStartServer.setObjectName(_fromUtf8("actionStartServer"))
        self.actionStopServer = QtGui.QAction(MainWindow)
        self.actionStopServer.setObjectName(_fromUtf8("actionStopServer"))
        self.actionConfigure_Server = QtGui.QAction(MainWindow)
        self.actionConfigure_Server.setObjectName(_fromUtf8("actionConfigure_Server"))
        self.actionSetupFilters = QtGui.QAction(MainWindow)
        self.actionSetupFilters.setObjectName(_fromUtf8("actionSetupFilters"))
        self.actionRunSettings = QtGui.QAction(MainWindow)
        self.actionRunSettings.setObjectName(_fromUtf8("actionRunSettings"))
        self.menuRemote_Server.addAction(self.actionConnect)
        self.menuRemote_Server.addAction(self.actionDisconnect)
        self.menuRemote_Server.addSeparator()
        self.menuRemote_Server.addAction(self.actionExit)
        self.menuLocal_Server.addAction(self.actionStartServer)
        self.menuLocal_Server.addAction(self.actionStopServer)
        self.menuFilter.addAction(self.actionSetupFilters)
        self.menuSettings.addAction(self.actionRunSettings)
        self.menubar.addAction(self.menuRemote_Server.menuAction())
        self.menubar.addAction(self.menuLocal_Server.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.clientsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Moderat Viewer", None))
        self.viewLogsButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.noteButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.logSettingsButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.setAliasButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.updateSourceButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.shellButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.explorerButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.scriptingButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.screenshotButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.webcamButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.clientsTable.setSortingEnabled(False)
        item = self.clientsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ip Address", None))
        item = self.clientsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.clientsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User", None))
        item = self.clientsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Alias", None))
        item = self.clientsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Active Window Title", None))
        self.clientsTabs.setTabText(self.clientsTabs.indexOf(self.onlineClientsTab), _translate("MainWindow", "Remote", None))
        self.directShellButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.directExplorerButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.directScriptingButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.directScreenshotButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.directWebcamButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.directClientsTable.setSortingEnabled(False)
        item = self.directClientsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ip Address", None))
        item = self.directClientsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.directClientsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Comment", None))
        self.clientsTabs.setTabText(self.clientsTabs.indexOf(self.directTab), _translate("MainWindow", "Direct", None))
        self.viewOfflineLogsButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.setOfflineAliasButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.removeClientButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.offlineClientsTable.setSortingEnabled(False)
        item = self.offlineClientsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Moderator", None))
        item = self.offlineClientsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.offlineClientsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alias", None))
        item = self.offlineClientsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ip Address", None))
        item = self.offlineClientsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Last Online", None))
        self.clientsTabs.setTabText(self.clientsTabs.indexOf(self.offlineClientsTab), _translate("MainWindow", "Offline", None))
        self.addModeratorButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.changePasswordButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.changePrivilegesButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.removeModeratorButton.setProperty("mainMenu", _translate("MainWindow", "1", None))
        self.moderatorsTable.setSortingEnabled(False)
        item = self.moderatorsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.moderatorsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Online Clients", None))
        item = self.moderatorsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Offline Clients", None))
        item = self.moderatorsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Privileges", None))
        item = self.moderatorsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.moderatorsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Last Online", None))
        self.onlineClientsCountLabel.setText(_translate("MainWindow", "0", None))
        self.offlineClientsCountLabel.setText(_translate("MainWindow", "0", None))
        self.clientsTabs.setTabText(self.clientsTabs.indexOf(self.moderatorsTab), _translate("MainWindow", "Moderators", None))
        self.menuRemote_Server.setTitle(_translate("MainWindow", "Remote Server", None))
        self.menuLocal_Server.setTitle(_translate("MainWindow", "Local Server", None))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.actionStartListen_for_connections.setText(_translate("MainWindow", "Connect", None))
        self.actionStopListen_for_connections.setText(_translate("MainWindow", "Disconnect", None))
        self.actionViewer_Configuration.setText(_translate("MainWindow", "Settings", None))
        self.actionRemote_Shell.setText(_translate("MainWindow", "Remote Shell", None))
        self.actionRemote_Explorer.setText(_translate("MainWindow", "Remote File Manager", None))
        self.actionRemote_Process_Manager.setText(_translate("MainWindow", "Remote Process Manager", None))
        self.actionRemote_Microphone.setText(_translate("MainWindow", "Remote Microphone", None))
        self.actionRemote_Scripting.setText(_translate("MainWindow", "Remote Scripting", None))
        self.actionRemote_Keylogger.setText(_translate("MainWindow", "Remote Keylogger", None))
        self.actionDesktop_Preview.setText(_translate("MainWindow", "Desktop Preview", None))
        self.actionWebcam_Preview.setText(_translate("MainWindow", "Webcam Preview", None))
        self.actionStop_Client.setText(_translate("MainWindow", "Stop", None))
        self.actionLock_Client.setText(_translate("MainWindow", "Lock", None))
        self.actionLog_off.setText(_translate("MainWindow", "Log off", None))
        self.actionReboot.setText(_translate("MainWindow", "Reboot", None))
        self.actionShutdown.setText(_translate("MainWindow", "Shutdown", None))
        self.actionUnlock_Client.setText(_translate("MainWindow", "Unlock", None))
        self.actionSet_Alias.setText(_translate("MainWindow", "Set Alias", None))
        self.actionRun_As_Admin.setText(_translate("MainWindow", "Run As Admin", None))
        self.actionTerminate_Client.setText(_translate("MainWindow", "Terminate", None))
        self.actionWindows_Client_PyInstaller.setText(_translate("MainWindow", "Windows Client (PyInstaller 3.0)", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionStartServer.setText(_translate("MainWindow", "Start Server", None))
        self.actionStopServer.setText(_translate("MainWindow", "Stop Server", None))
        self.actionConfigure_Server.setText(_translate("MainWindow", "Configure Server", None))
        self.actionSetupFilters.setText(_translate("MainWindow", "Setup Filters", None))
        self.actionRunSettings.setText(_translate("MainWindow", "Run Settings", None))

import res_rc
