# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(799, 459)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.saveButton = QtGui.QPushButton(Form)
        self.saveButton.setMinimumSize(QtCore.QSize(100, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/save_as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout.addWidget(self.saveButton)
        self.closeButton = QtGui.QPushButton(Form)
        self.closeButton.setMinimumSize(QtCore.QSize(100, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout.addWidget(self.closeButton)
        self.applyButton = QtGui.QPushButton(Form)
        self.applyButton.setMinimumSize(QtCore.QSize(100, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/checkbox-check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.applyButton.setIcon(icon3)
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.horizontalLayout.addWidget(self.applyButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.settingsTab = QtGui.QTabWidget(Form)
        self.settingsTab.setElideMode(QtCore.Qt.ElideNone)
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.appearanceTab = QtGui.QWidget()
        self.appearanceTab.setObjectName(_fromUtf8("appearanceTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.appearanceTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.settingsAppearanceTab = QtGui.QTabWidget(self.appearanceTab)
        self.settingsAppearanceTab.setObjectName(_fromUtf8("settingsAppearanceTab"))
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName(_fromUtf8("generalTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.generalTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.interfaceGroup = QtGui.QGroupBox(self.generalTab)
        self.interfaceGroup.setObjectName(_fromUtf8("interfaceGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.interfaceGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.themeLabel = QtGui.QLabel(self.interfaceGroup)
        self.themeLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.themeLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.themeLabel.setObjectName(_fromUtf8("themeLabel"))
        self.horizontalLayout_8.addWidget(self.themeLabel)
        self.themeCombo = QtGui.QComboBox(self.interfaceGroup)
        self.themeCombo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.themeCombo.setObjectName(_fromUtf8("themeCombo"))
        self.themeCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.themeCombo)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.languageLabel = QtGui.QLabel(self.interfaceGroup)
        self.languageLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.languageLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.languageLabel.setObjectName(_fromUtf8("languageLabel"))
        self.horizontalLayout_2.addWidget(self.languageLabel)
        self.languageCombo = QtGui.QComboBox(self.interfaceGroup)
        self.languageCombo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.languageCombo.setObjectName(_fromUtf8("languageCombo"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/flags/us.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.languageCombo.addItem(icon4, _fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/flags/ge.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.languageCombo.addItem(icon5, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.languageCombo)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.opacityLabel = QtGui.QLabel(self.interfaceGroup)
        self.opacityLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.opacityLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.opacityLabel.setObjectName(_fromUtf8("opacityLabel"))
        self.horizontalLayout_13.addWidget(self.opacityLabel)
        self.opacitySlider = QtGui.QSlider(self.interfaceGroup)
        self.opacitySlider.setMaximum(100)
        self.opacitySlider.setPageStep(1)
        self.opacitySlider.setProperty("value", 90)
        self.opacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider.setInvertedAppearance(False)
        self.opacitySlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.opacitySlider.setTickInterval(10)
        self.opacitySlider.setObjectName(_fromUtf8("opacitySlider"))
        self.horizontalLayout_13.addWidget(self.opacitySlider)
        self.sliderValueLabel = QtGui.QLabel(self.interfaceGroup)
        self.sliderValueLabel.setObjectName(_fromUtf8("sliderValueLabel"))
        self.horizontalLayout_13.addWidget(self.sliderValueLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.interfaceGroup, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 2, 0, 1, 1)
        self.settingsAppearanceTab.addTab(self.generalTab, icon, _fromUtf8(""))
        self.onlineTab = QtGui.QWidget()
        self.onlineTab.setObjectName(_fromUtf8("onlineTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.onlineTab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.headersGroup = QtGui.QGroupBox(self.onlineTab)
        self.headersGroup.setObjectName(_fromUtf8("headersGroup"))
        self.gridLayout_6 = QtGui.QGridLayout(self.headersGroup)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ipaddressHeaderCheck = QtGui.QCheckBox(self.headersGroup)
        self.ipaddressHeaderCheck.setChecked(True)
        self.ipaddressHeaderCheck.setObjectName(_fromUtf8("ipaddressHeaderCheck"))
        self.gridLayout_6.addWidget(self.ipaddressHeaderCheck, 0, 0, 1, 1)
        self.aliasHeaderCheck = QtGui.QCheckBox(self.headersGroup)
        self.aliasHeaderCheck.setChecked(True)
        self.aliasHeaderCheck.setObjectName(_fromUtf8("aliasHeaderCheck"))
        self.gridLayout_6.addWidget(self.aliasHeaderCheck, 1, 1, 1, 1)
        self.clientIdHeaderCheck = QtGui.QCheckBox(self.headersGroup)
        self.clientIdHeaderCheck.setChecked(True)
        self.clientIdHeaderCheck.setObjectName(_fromUtf8("clientIdHeaderCheck"))
        self.gridLayout_6.addWidget(self.clientIdHeaderCheck, 0, 1, 1, 1)
        self.userHeaderCheck = QtGui.QCheckBox(self.headersGroup)
        self.userHeaderCheck.setChecked(True)
        self.userHeaderCheck.setObjectName(_fromUtf8("userHeaderCheck"))
        self.gridLayout_6.addWidget(self.userHeaderCheck, 1, 0, 1, 1)
        self.titleHeaderCheck = QtGui.QCheckBox(self.headersGroup)
        self.titleHeaderCheck.setChecked(True)
        self.titleHeaderCheck.setObjectName(_fromUtf8("titleHeaderCheck"))
        self.gridLayout_6.addWidget(self.titleHeaderCheck, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.headersGroup, 1, 0, 1, 1)
        self.appearanceGroup = QtGui.QGroupBox(self.onlineTab)
        self.appearanceGroup.setObjectName(_fromUtf8("appearanceGroup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.appearanceGroup)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.onlinePerPageLabel = QtGui.QLabel(self.appearanceGroup)
        self.onlinePerPageLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.onlinePerPageLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.onlinePerPageLabel.setObjectName(_fromUtf8("onlinePerPageLabel"))
        self.horizontalLayout_3.addWidget(self.onlinePerPageLabel)
        self.onlinePerPageLine = QtGui.QLineEdit(self.appearanceGroup)
        self.onlinePerPageLine.setObjectName(_fromUtf8("onlinePerPageLine"))
        self.horizontalLayout_3.addWidget(self.onlinePerPageLine)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.appearanceGroup, 0, 0, 1, 1)
        self.menuGroup = QtGui.QGroupBox(self.onlineTab)
        self.menuGroup.setObjectName(_fromUtf8("menuGroup"))
        self.gridLayout_5 = QtGui.QGridLayout(self.menuGroup)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.shellCheck = QtGui.QCheckBox(self.menuGroup)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/remote_shell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shellCheck.setIcon(icon6)
        self.shellCheck.setChecked(True)
        self.shellCheck.setObjectName(_fromUtf8("shellCheck"))
        self.gridLayout_5.addWidget(self.shellCheck, 1, 1, 1, 1)
        self.updateCheck = QtGui.QCheckBox(self.menuGroup)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/update_source.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateCheck.setIcon(icon7)
        self.updateCheck.setChecked(True)
        self.updateCheck.setObjectName(_fromUtf8("updateCheck"))
        self.gridLayout_5.addWidget(self.updateCheck, 1, 0, 1, 1)
        self.logViewerCheck = QtGui.QCheckBox(self.menuGroup)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/log_viewer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logViewerCheck.setIcon(icon8)
        self.logViewerCheck.setChecked(True)
        self.logViewerCheck.setObjectName(_fromUtf8("logViewerCheck"))
        self.gridLayout_5.addWidget(self.logViewerCheck, 0, 0, 1, 1)
        self.explorerCheck = QtGui.QCheckBox(self.menuGroup)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/remote_explorer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.explorerCheck.setIcon(icon9)
        self.explorerCheck.setChecked(True)
        self.explorerCheck.setObjectName(_fromUtf8("explorerCheck"))
        self.gridLayout_5.addWidget(self.explorerCheck, 1, 2, 1, 1)
        self.noteCheck = QtGui.QCheckBox(self.menuGroup)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/note.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noteCheck.setIcon(icon10)
        self.noteCheck.setChecked(True)
        self.noteCheck.setObjectName(_fromUtf8("noteCheck"))
        self.gridLayout_5.addWidget(self.noteCheck, 0, 1, 1, 1)
        self.aliasCheck = QtGui.QCheckBox(self.menuGroup)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/set_alias.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aliasCheck.setIcon(icon11)
        self.aliasCheck.setChecked(True)
        self.aliasCheck.setObjectName(_fromUtf8("aliasCheck"))
        self.gridLayout_5.addWidget(self.aliasCheck, 0, 2, 1, 1)
        self.scriptingCheck = QtGui.QCheckBox(self.menuGroup)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/remote_scripting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scriptingCheck.setIcon(icon12)
        self.scriptingCheck.setChecked(True)
        self.scriptingCheck.setObjectName(_fromUtf8("scriptingCheck"))
        self.gridLayout_5.addWidget(self.scriptingCheck, 2, 0, 1, 1)
        self.screenshotCheck = QtGui.QCheckBox(self.menuGroup)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/desktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotCheck.setIcon(icon13)
        self.screenshotCheck.setChecked(True)
        self.screenshotCheck.setObjectName(_fromUtf8("screenshotCheck"))
        self.gridLayout_5.addWidget(self.screenshotCheck, 2, 1, 1, 1)
        self.webcamCheck = QtGui.QCheckBox(self.menuGroup)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/webcam.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webcamCheck.setIcon(icon14)
        self.webcamCheck.setChecked(True)
        self.webcamCheck.setObjectName(_fromUtf8("webcamCheck"))
        self.gridLayout_5.addWidget(self.webcamCheck, 2, 2, 1, 1)
        self.gridLayout_8.addWidget(self.menuGroup, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 3, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/online_clients.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsAppearanceTab.addTab(self.onlineTab, icon15, _fromUtf8(""))
        self.offlineTab = QtGui.QWidget()
        self.offlineTab.setObjectName(_fromUtf8("offlineTab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.offlineTab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.appearanceGroup_2 = QtGui.QGroupBox(self.offlineTab)
        self.appearanceGroup_2.setObjectName(_fromUtf8("appearanceGroup_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.appearanceGroup_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.offlinePerPageLabel = QtGui.QLabel(self.appearanceGroup_2)
        self.offlinePerPageLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.offlinePerPageLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.offlinePerPageLabel.setObjectName(_fromUtf8("offlinePerPageLabel"))
        self.horizontalLayout_6.addWidget(self.offlinePerPageLabel)
        self.offlinePerPageLine = QtGui.QLineEdit(self.appearanceGroup_2)
        self.offlinePerPageLine.setObjectName(_fromUtf8("offlinePerPageLine"))
        self.horizontalLayout_6.addWidget(self.offlinePerPageLine)
        self.gridLayout_9.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.appearanceGroup_2, 0, 0, 1, 2)
        self.menuGroup_2 = QtGui.QGroupBox(self.offlineTab)
        self.menuGroup_2.setObjectName(_fromUtf8("menuGroup_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.menuGroup_2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.offlineLogViewerCheck = QtGui.QCheckBox(self.menuGroup_2)
        self.offlineLogViewerCheck.setIcon(icon8)
        self.offlineLogViewerCheck.setChecked(True)
        self.offlineLogViewerCheck.setObjectName(_fromUtf8("offlineLogViewerCheck"))
        self.gridLayout_11.addWidget(self.offlineLogViewerCheck, 0, 0, 1, 1)
        self.offlineNoteCheck = QtGui.QCheckBox(self.menuGroup_2)
        self.offlineNoteCheck.setIcon(icon10)
        self.offlineNoteCheck.setChecked(True)
        self.offlineNoteCheck.setObjectName(_fromUtf8("offlineNoteCheck"))
        self.gridLayout_11.addWidget(self.offlineNoteCheck, 0, 1, 1, 1)
        self.offlineRemoveCheck = QtGui.QCheckBox(self.menuGroup_2)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/trash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offlineRemoveCheck.setIcon(icon16)
        self.offlineRemoveCheck.setChecked(True)
        self.offlineRemoveCheck.setObjectName(_fromUtf8("offlineRemoveCheck"))
        self.gridLayout_11.addWidget(self.offlineRemoveCheck, 1, 1, 1, 1)
        self.offlineAliasCheck = QtGui.QCheckBox(self.menuGroup_2)
        self.offlineAliasCheck.setIcon(icon11)
        self.offlineAliasCheck.setChecked(True)
        self.offlineAliasCheck.setObjectName(_fromUtf8("offlineAliasCheck"))
        self.gridLayout_11.addWidget(self.offlineAliasCheck, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.menuGroup_2, 2, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 83, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem3, 3, 1, 1, 1)
        self.headersGroup_2 = QtGui.QGroupBox(self.offlineTab)
        self.headersGroup_2.setObjectName(_fromUtf8("headersGroup_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.headersGroup_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.offlineIpaddressHeaderCheck = QtGui.QCheckBox(self.headersGroup_2)
        self.offlineIpaddressHeaderCheck.setChecked(True)
        self.offlineIpaddressHeaderCheck.setObjectName(_fromUtf8("offlineIpaddressHeaderCheck"))
        self.gridLayout_10.addWidget(self.offlineIpaddressHeaderCheck, 0, 0, 1, 1)
        self.offlineClientIdHeaderCheck = QtGui.QCheckBox(self.headersGroup_2)
        self.offlineClientIdHeaderCheck.setChecked(True)
        self.offlineClientIdHeaderCheck.setObjectName(_fromUtf8("offlineClientIdHeaderCheck"))
        self.gridLayout_10.addWidget(self.offlineClientIdHeaderCheck, 0, 1, 1, 1)
        self.offlineAliasHeaderCheck = QtGui.QCheckBox(self.headersGroup_2)
        self.offlineAliasHeaderCheck.setChecked(True)
        self.offlineAliasHeaderCheck.setObjectName(_fromUtf8("offlineAliasHeaderCheck"))
        self.gridLayout_10.addWidget(self.offlineAliasHeaderCheck, 1, 0, 1, 1)
        self.offlineLastOnlineHeaderCheck = QtGui.QCheckBox(self.headersGroup_2)
        self.offlineLastOnlineHeaderCheck.setChecked(True)
        self.offlineLastOnlineHeaderCheck.setObjectName(_fromUtf8("offlineLastOnlineHeaderCheck"))
        self.gridLayout_10.addWidget(self.offlineLastOnlineHeaderCheck, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.headersGroup_2, 1, 0, 1, 2)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/offline_clients.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsAppearanceTab.addTab(self.offlineTab, icon17, _fromUtf8(""))
        self.directTab = QtGui.QWidget()
        self.directTab.setObjectName(_fromUtf8("directTab"))
        self.gridLayout_19 = QtGui.QGridLayout(self.directTab)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.menuGroup_3 = QtGui.QGroupBox(self.directTab)
        self.menuGroup_3.setObjectName(_fromUtf8("menuGroup_3"))
        self.gridLayout_18 = QtGui.QGridLayout(self.menuGroup_3)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.directShellCheck = QtGui.QCheckBox(self.menuGroup_3)
        self.directShellCheck.setIcon(icon6)
        self.directShellCheck.setChecked(True)
        self.directShellCheck.setObjectName(_fromUtf8("directShellCheck"))
        self.gridLayout_18.addWidget(self.directShellCheck, 0, 1, 1, 1)
        self.directExplorerCheck = QtGui.QCheckBox(self.menuGroup_3)
        self.directExplorerCheck.setIcon(icon9)
        self.directExplorerCheck.setChecked(True)
        self.directExplorerCheck.setObjectName(_fromUtf8("directExplorerCheck"))
        self.gridLayout_18.addWidget(self.directExplorerCheck, 0, 2, 1, 1)
        self.directScriptingCheck = QtGui.QCheckBox(self.menuGroup_3)
        self.directScriptingCheck.setIcon(icon12)
        self.directScriptingCheck.setChecked(True)
        self.directScriptingCheck.setObjectName(_fromUtf8("directScriptingCheck"))
        self.gridLayout_18.addWidget(self.directScriptingCheck, 0, 3, 1, 1)
        self.directScreenshotCheck = QtGui.QCheckBox(self.menuGroup_3)
        self.directScreenshotCheck.setIcon(icon13)
        self.directScreenshotCheck.setChecked(True)
        self.directScreenshotCheck.setObjectName(_fromUtf8("directScreenshotCheck"))
        self.gridLayout_18.addWidget(self.directScreenshotCheck, 1, 1, 1, 1)
        self.directWebcamCheck = QtGui.QCheckBox(self.menuGroup_3)
        self.directWebcamCheck.setIcon(icon14)
        self.directWebcamCheck.setChecked(True)
        self.directWebcamCheck.setObjectName(_fromUtf8("directWebcamCheck"))
        self.gridLayout_18.addWidget(self.directWebcamCheck, 1, 2, 1, 1)
        self.gridLayout_19.addWidget(self.menuGroup_3, 1, 0, 1, 1)
        self.headersGroup_3 = QtGui.QGroupBox(self.directTab)
        self.headersGroup_3.setObjectName(_fromUtf8("headersGroup_3"))
        self.gridLayout_17 = QtGui.QGridLayout(self.headersGroup_3)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.directClientIdHeaderCheck = QtGui.QCheckBox(self.headersGroup_3)
        self.directClientIdHeaderCheck.setChecked(True)
        self.directClientIdHeaderCheck.setObjectName(_fromUtf8("directClientIdHeaderCheck"))
        self.gridLayout_17.addWidget(self.directClientIdHeaderCheck, 0, 1, 1, 1)
        self.directIpaddressHeaderCheck = QtGui.QCheckBox(self.headersGroup_3)
        self.directIpaddressHeaderCheck.setChecked(True)
        self.directIpaddressHeaderCheck.setObjectName(_fromUtf8("directIpaddressHeaderCheck"))
        self.gridLayout_17.addWidget(self.directIpaddressHeaderCheck, 0, 0, 1, 1)
        self.directCommentHeaderCheck = QtGui.QCheckBox(self.headersGroup_3)
        self.directCommentHeaderCheck.setChecked(True)
        self.directCommentHeaderCheck.setObjectName(_fromUtf8("directCommentHeaderCheck"))
        self.gridLayout_17.addWidget(self.directCommentHeaderCheck, 0, 2, 1, 1)
        self.gridLayout_19.addWidget(self.headersGroup_3, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem4, 2, 0, 1, 1)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsAppearanceTab.addTab(self.directTab, icon18, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.settingsAppearanceTab, 0, 0, 1, 1)
        self.settingsTab.addTab(self.appearanceTab, _fromUtf8(""))
        self.connetionTab = QtGui.QWidget()
        self.connetionTab.setObjectName(_fromUtf8("connetionTab"))
        self.gridLayout_14 = QtGui.QGridLayout(self.connetionTab)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.remoteServerGroup = QtGui.QGroupBox(self.connetionTab)
        self.remoteServerGroup.setObjectName(_fromUtf8("remoteServerGroup"))
        self.gridLayout_13 = QtGui.QGridLayout(self.remoteServerGroup)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.remoteServerIpAddressLabel = QtGui.QLabel(self.remoteServerGroup)
        self.remoteServerIpAddressLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.remoteServerIpAddressLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.remoteServerIpAddressLabel.setObjectName(_fromUtf8("remoteServerIpAddressLabel"))
        self.horizontalLayout_4.addWidget(self.remoteServerIpAddressLabel)
        self.remoteServerIpAddressLine = QtGui.QLineEdit(self.remoteServerGroup)
        self.remoteServerIpAddressLine.setObjectName(_fromUtf8("remoteServerIpAddressLine"))
        self.horizontalLayout_4.addWidget(self.remoteServerIpAddressLine)
        self.gridLayout_13.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.remoteServerPortLabel = QtGui.QLabel(self.remoteServerGroup)
        self.remoteServerPortLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.remoteServerPortLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.remoteServerPortLabel.setObjectName(_fromUtf8("remoteServerPortLabel"))
        self.horizontalLayout_5.addWidget(self.remoteServerPortLabel)
        self.remoteServerPortLine = QtGui.QLineEdit(self.remoteServerGroup)
        self.remoteServerPortLine.setObjectName(_fromUtf8("remoteServerPortLine"))
        self.horizontalLayout_5.addWidget(self.remoteServerPortLine)
        self.gridLayout_13.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.gridLayout_14.addWidget(self.remoteServerGroup, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem5, 3, 0, 1, 1)
        self.serverDefaultValuesGroup = QtGui.QGroupBox(self.connetionTab)
        self.serverDefaultValuesGroup.setObjectName(_fromUtf8("serverDefaultValuesGroup"))
        self.gridLayout_21 = QtGui.QGridLayout(self.serverDefaultValuesGroup)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.remoteUsernameValueLabel = QtGui.QLabel(self.serverDefaultValuesGroup)
        self.remoteUsernameValueLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.remoteUsernameValueLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.remoteUsernameValueLabel.setObjectName(_fromUtf8("remoteUsernameValueLabel"))
        self.horizontalLayout_7.addWidget(self.remoteUsernameValueLabel)
        self.remoteServerUsernameLine = QtGui.QLineEdit(self.serverDefaultValuesGroup)
        self.remoteServerUsernameLine.setText(_fromUtf8(""))
        self.remoteServerUsernameLine.setObjectName(_fromUtf8("remoteServerUsernameLine"))
        self.horizontalLayout_7.addWidget(self.remoteServerUsernameLine)
        self.gridLayout_21.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.serverDefaultValuesGroup, 1, 0, 1, 1)
        self.settingsTab.addTab(self.connetionTab, _fromUtf8(""))
        self.serverTab = QtGui.QWidget()
        self.serverTab.setObjectName(_fromUtf8("serverTab"))
        self.gridLayout_16 = QtGui.QGridLayout(self.serverTab)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.directServerGroup = QtGui.QGroupBox(self.serverTab)
        self.directServerGroup.setObjectName(_fromUtf8("directServerGroup"))
        self.gridLayout_15 = QtGui.QGridLayout(self.directServerGroup)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.directServerPortLabel = QtGui.QLabel(self.directServerGroup)
        self.directServerPortLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.directServerPortLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.directServerPortLabel.setObjectName(_fromUtf8("directServerPortLabel"))
        self.horizontalLayout_9.addWidget(self.directServerPortLabel)
        self.directServerPortLine = QtGui.QLineEdit(self.directServerGroup)
        self.directServerPortLine.setObjectName(_fromUtf8("directServerPortLine"))
        self.horizontalLayout_9.addWidget(self.directServerPortLine)
        self.gridLayout_15.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.directServerGroup, 0, 0, 1, 1)
        self.directDefaultValues = QtGui.QGroupBox(self.serverTab)
        self.directDefaultValues.setObjectName(_fromUtf8("directDefaultValues"))
        self.gridLayout_20 = QtGui.QGridLayout(self.directDefaultValues)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.directIpAddressValueLabel = QtGui.QLabel(self.directDefaultValues)
        self.directIpAddressValueLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.directIpAddressValueLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.directIpAddressValueLabel.setObjectName(_fromUtf8("directIpAddressValueLabel"))
        self.horizontalLayout_10.addWidget(self.directIpAddressValueLabel)
        self.directIpAddressValueLine = QtGui.QLineEdit(self.directDefaultValues)
        self.directIpAddressValueLine.setObjectName(_fromUtf8("directIpAddressValueLine"))
        self.horizontalLayout_10.addWidget(self.directIpAddressValueLine)
        self.internalIpButton = QtGui.QPushButton(self.directDefaultValues)
        self.internalIpButton.setText(_fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/lan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.internalIpButton.setIcon(icon19)
        self.internalIpButton.setObjectName(_fromUtf8("internalIpButton"))
        self.horizontalLayout_10.addWidget(self.internalIpButton)
        self.externalIpButton = QtGui.QPushButton(self.directDefaultValues)
        self.externalIpButton.setText(_fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/wan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.externalIpButton.setIcon(icon20)
        self.externalIpButton.setObjectName(_fromUtf8("externalIpButton"))
        self.horizontalLayout_10.addWidget(self.externalIpButton)
        self.gridLayout_20.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.directPortValueLabel = QtGui.QLabel(self.directDefaultValues)
        self.directPortValueLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.directPortValueLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.directPortValueLabel.setObjectName(_fromUtf8("directPortValueLabel"))
        self.horizontalLayout_11.addWidget(self.directPortValueLabel)
        self.directPortValueLine = QtGui.QLineEdit(self.directDefaultValues)
        self.directPortValueLine.setObjectName(_fromUtf8("directPortValueLine"))
        self.horizontalLayout_11.addWidget(self.directPortValueLine)
        self.gridLayout_20.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.directCommentValueLabel = QtGui.QLabel(self.directDefaultValues)
        self.directCommentValueLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.directCommentValueLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.directCommentValueLabel.setObjectName(_fromUtf8("directCommentValueLabel"))
        self.horizontalLayout_12.addWidget(self.directCommentValueLabel)
        self.directCommentValueLine = QtGui.QLineEdit(self.directDefaultValues)
        self.directCommentValueLine.setText(_fromUtf8(""))
        self.directCommentValueLine.setObjectName(_fromUtf8("directCommentValueLine"))
        self.horizontalLayout_12.addWidget(self.directCommentValueLine)
        self.gridLayout_20.addLayout(self.horizontalLayout_12, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.directDefaultValues, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem6, 2, 0, 1, 1)
        self.settingsTab.addTab(self.serverTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.settingsTab, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.settingsTab.setCurrentIndex(0)
        self.settingsAppearanceTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.opacitySlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sliderValueLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Moderat Settings", None))
        self.saveButton.setText(_translate("Form", "Save", None))
        self.closeButton.setText(_translate("Form", "Close", None))
        self.applyButton.setText(_translate("Form", "Apply", None))
        self.interfaceGroup.setTitle(_translate("Form", "Interface", None))
        self.themeLabel.setText(_translate("Form", "Theme:", None))
        self.themeCombo.setItemText(0, _translate("Form", "DarkBlue", None))
        self.languageLabel.setText(_translate("Form", "Language: ", None))
        self.languageCombo.setItemText(0, _translate("Form", "English", None))
        self.languageCombo.setItemText(1, _translate("Form", "Georgian", None))
        self.opacityLabel.setText(_translate("Form", "Opacity:", None))
        self.sliderValueLabel.setText(_translate("Form", "90", None))
        self.settingsAppearanceTab.setTabText(self.settingsAppearanceTab.indexOf(self.generalTab), _translate("Form", "General", None))
        self.headersGroup.setTitle(_translate("Form", "Headers", None))
        self.ipaddressHeaderCheck.setText(_translate("Form", "IP Address", None))
        self.aliasHeaderCheck.setText(_translate("Form", "Alias", None))
        self.clientIdHeaderCheck.setText(_translate("Form", "Client ID", None))
        self.userHeaderCheck.setText(_translate("Form", "User", None))
        self.titleHeaderCheck.setText(_translate("Form", "Active Window Title", None))
        self.appearanceGroup.setTitle(_translate("Form", "Appearance", None))
        self.onlinePerPageLabel.setText(_translate("Form", "Online Clients Per Page:", None))
        self.onlinePerPageLine.setText(_translate("Form", "15", None))
        self.menuGroup.setTitle(_translate("Form", "Menu", None))
        self.shellCheck.setText(_translate("Form", "Shell", None))
        self.updateCheck.setText(_translate("Form", "Update", None))
        self.logViewerCheck.setText(_translate("Form", "Log Viewer", None))
        self.explorerCheck.setText(_translate("Form", "Explorer", None))
        self.noteCheck.setText(_translate("Form", "Note", None))
        self.aliasCheck.setText(_translate("Form", "Set Alias", None))
        self.scriptingCheck.setText(_translate("Form", "Scripting", None))
        self.screenshotCheck.setText(_translate("Form", "Screenshot", None))
        self.webcamCheck.setText(_translate("Form", "Web Camera", None))
        self.settingsAppearanceTab.setTabText(self.settingsAppearanceTab.indexOf(self.onlineTab), _translate("Form", "Online", None))
        self.appearanceGroup_2.setTitle(_translate("Form", "Appearance", None))
        self.offlinePerPageLabel.setText(_translate("Form", "Offline Clients Per Page:", None))
        self.offlinePerPageLine.setText(_translate("Form", "15", None))
        self.menuGroup_2.setTitle(_translate("Form", "Menu", None))
        self.offlineLogViewerCheck.setText(_translate("Form", "Log Viewer", None))
        self.offlineNoteCheck.setText(_translate("Form", "Note", None))
        self.offlineRemoveCheck.setText(_translate("Form", "Remove", None))
        self.offlineAliasCheck.setText(_translate("Form", "Set Alias", None))
        self.headersGroup_2.setTitle(_translate("Form", "Headers", None))
        self.offlineIpaddressHeaderCheck.setText(_translate("Form", "IP Address", None))
        self.offlineClientIdHeaderCheck.setText(_translate("Form", "Client ID", None))
        self.offlineAliasHeaderCheck.setText(_translate("Form", "Alias", None))
        self.offlineLastOnlineHeaderCheck.setText(_translate("Form", "Last Online", None))
        self.settingsAppearanceTab.setTabText(self.settingsAppearanceTab.indexOf(self.offlineTab), _translate("Form", "Offline", None))
        self.menuGroup_3.setTitle(_translate("Form", "Menu", None))
        self.directShellCheck.setText(_translate("Form", "Shell", None))
        self.directExplorerCheck.setText(_translate("Form", "Explorer", None))
        self.directScriptingCheck.setText(_translate("Form", "Scripting", None))
        self.directScreenshotCheck.setText(_translate("Form", "Screenshot", None))
        self.directWebcamCheck.setText(_translate("Form", "Web Camera", None))
        self.headersGroup_3.setTitle(_translate("Form", "Headers", None))
        self.directClientIdHeaderCheck.setText(_translate("Form", "Client ID", None))
        self.directIpaddressHeaderCheck.setText(_translate("Form", "IP Address", None))
        self.directCommentHeaderCheck.setText(_translate("Form", "Comment", None))
        self.settingsAppearanceTab.setTabText(self.settingsAppearanceTab.indexOf(self.directTab), _translate("Form", "Direct", None))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.appearanceTab), _translate("Form", "Appearance", None))
        self.remoteServerGroup.setTitle(_translate("Form", "Server", None))
        self.remoteServerIpAddressLabel.setText(_translate("Form", "Server IP Address: ", None))
        self.remoteServerIpAddressLine.setText(_translate("Form", "127.0.0.1", None))
        self.remoteServerPortLabel.setText(_translate("Form", "Server Port: ", None))
        self.remoteServerPortLine.setText(_translate("Form", "5545", None))
        self.serverDefaultValuesGroup.setTitle(_translate("Form", "Default Values", None))
        self.remoteUsernameValueLabel.setText(_translate("Form", "Username: ", None))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.connetionTab), _translate("Form", "Remote Server", None))
        self.directServerGroup.setTitle(_translate("Form", "Server Settings", None))
        self.directServerPortLabel.setText(_translate("Form", "Direct Server Port: ", None))
        self.directServerPortLine.setText(_translate("Form", "5595", None))
        self.directDefaultValues.setTitle(_translate("Form", "Default Values", None))
        self.directIpAddressValueLabel.setText(_translate("Form", "IP Address: ", None))
        self.directIpAddressValueLine.setText(_translate("Form", "127.0.0.1", None))
        self.directPortValueLabel.setText(_translate("Form", "Port: ", None))
        self.directPortValueLine.setText(_translate("Form", "5595", None))
        self.directCommentValueLabel.setText(_translate("Form", "Comment: ", None))
        self.settingsTab.setTabText(self.settingsTab.indexOf(self.serverTab), _translate("Form", "Direct Server", None))

import res_rc
