# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'htmleditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(659, 398)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.webView = QtWebKit.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayout.addWidget(self.webView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.standardToolBar = QtGui.QToolBar(MainWindow)
        self.standardToolBar.setIconSize(QtCore.QSize(16, 16))
        self.standardToolBar.setObjectName(_fromUtf8("standardToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.standardToolBar)
        self.formatToolBar = QtGui.QToolBar(MainWindow)
        self.formatToolBar.setIconSize(QtCore.QSize(16, 16))
        self.formatToolBar.setObjectName(_fromUtf8("formatToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.formatToolBar)
        MainWindow.insertToolBarBreak(self.formatToolBar)
        self.actionSave = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionEditUndo = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/edit-undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditUndo.setIcon(icon2)
        self.actionEditUndo.setObjectName(_fromUtf8("actionEditUndo"))
        self.actionEditRedo = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/edit-redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditRedo.setIcon(icon3)
        self.actionEditRedo.setObjectName(_fromUtf8("actionEditRedo"))
        self.actionEditCut = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/edit-cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditCut.setIcon(icon4)
        self.actionEditCut.setObjectName(_fromUtf8("actionEditCut"))
        self.actionEditCopy = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/edit-copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditCopy.setIcon(icon5)
        self.actionEditCopy.setObjectName(_fromUtf8("actionEditCopy"))
        self.actionEditPaste = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/edit-paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditPaste.setIcon(icon6)
        self.actionEditPaste.setObjectName(_fromUtf8("actionEditPaste"))
        self.actionEditSelectAll = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/edit-select-all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditSelectAll.setIcon(icon7)
        self.actionEditSelectAll.setObjectName(_fromUtf8("actionEditSelectAll"))
        self.actionFormatBold = QtGui.QAction(MainWindow)
        self.actionFormatBold.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-text-bold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatBold.setIcon(icon8)
        self.actionFormatBold.setObjectName(_fromUtf8("actionFormatBold"))
        self.actionFormatItalic = QtGui.QAction(MainWindow)
        self.actionFormatItalic.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-text-italic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatItalic.setIcon(icon9)
        self.actionFormatItalic.setObjectName(_fromUtf8("actionFormatItalic"))
        self.actionFormatUnderline = QtGui.QAction(MainWindow)
        self.actionFormatUnderline.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-text-underline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatUnderline.setIcon(icon10)
        self.actionFormatUnderline.setObjectName(_fromUtf8("actionFormatUnderline"))
        self.actionFormatStrikethrough = QtGui.QAction(MainWindow)
        self.actionFormatStrikethrough.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-text-strikethrough.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatStrikethrough.setIcon(icon11)
        self.actionFormatStrikethrough.setObjectName(_fromUtf8("actionFormatStrikethrough"))
        self.actionFormatFontSize = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/text-size.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatFontSize.setIcon(icon12)
        self.actionFormatFontSize.setText(_fromUtf8(""))
        self.actionFormatFontSize.setObjectName(_fromUtf8("actionFormatFontSize"))
        self.actionFormatTextColor = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/text-color.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatTextColor.setIcon(icon13)
        self.actionFormatTextColor.setText(_fromUtf8(""))
        self.actionFormatTextColor.setObjectName(_fromUtf8("actionFormatTextColor"))
        self.actionFormatBackgroundColor = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/background-color.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatBackgroundColor.setIcon(icon14)
        self.actionFormatBackgroundColor.setText(_fromUtf8(""))
        self.actionFormatBackgroundColor.setObjectName(_fromUtf8("actionFormatBackgroundColor"))
        self.actionFormatAlignLeft = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-justify-left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignLeft.setIcon(icon15)
        self.actionFormatAlignLeft.setObjectName(_fromUtf8("actionFormatAlignLeft"))
        self.actionFormatAlignCenter = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-justify-center.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignCenter.setIcon(icon16)
        self.actionFormatAlignCenter.setObjectName(_fromUtf8("actionFormatAlignCenter"))
        self.actionFormatAlignRight = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-justify-right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignRight.setIcon(icon17)
        self.actionFormatAlignRight.setObjectName(_fromUtf8("actionFormatAlignRight"))
        self.actionFormatAlignJustify = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-justify-fill.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatAlignJustify.setIcon(icon18)
        self.actionFormatAlignJustify.setObjectName(_fromUtf8("actionFormatAlignJustify"))
        self.actionFormatIncreaseIndent = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-indent-more.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatIncreaseIndent.setIcon(icon19)
        self.actionFormatIncreaseIndent.setObjectName(_fromUtf8("actionFormatIncreaseIndent"))
        self.actionFormatDecreaseIndent = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/format-indent-less.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatDecreaseIndent.setIcon(icon20)
        self.actionFormatDecreaseIndent.setObjectName(_fromUtf8("actionFormatDecreaseIndent"))
        self.actionFormatBulletedList = QtGui.QAction(MainWindow)
        self.actionFormatBulletedList.setCheckable(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/bulleted-list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatBulletedList.setIcon(icon21)
        self.actionFormatBulletedList.setObjectName(_fromUtf8("actionFormatBulletedList"))
        self.actionFormatNumberedList = QtGui.QAction(MainWindow)
        self.actionFormatNumberedList.setCheckable(True)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/numbered-list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormatNumberedList.setIcon(icon22)
        self.actionFormatNumberedList.setObjectName(_fromUtf8("actionFormatNumberedList"))
        self.actionZoomOut = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon23)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionZoomIn = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/images/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon24)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionStyleParagraph = QtGui.QAction(MainWindow)
        self.actionStyleParagraph.setObjectName(_fromUtf8("actionStyleParagraph"))
        self.actionStyleHeading1 = QtGui.QAction(MainWindow)
        self.actionStyleHeading1.setObjectName(_fromUtf8("actionStyleHeading1"))
        self.actionStyleHeading2 = QtGui.QAction(MainWindow)
        self.actionStyleHeading2.setObjectName(_fromUtf8("actionStyleHeading2"))
        self.actionStyleHeading3 = QtGui.QAction(MainWindow)
        self.actionStyleHeading3.setObjectName(_fromUtf8("actionStyleHeading3"))
        self.actionStyleHeading4 = QtGui.QAction(MainWindow)
        self.actionStyleHeading4.setObjectName(_fromUtf8("actionStyleHeading4"))
        self.actionStyleHeading5 = QtGui.QAction(MainWindow)
        self.actionStyleHeading5.setObjectName(_fromUtf8("actionStyleHeading5"))
        self.actionStyleHeading6 = QtGui.QAction(MainWindow)
        self.actionStyleHeading6.setObjectName(_fromUtf8("actionStyleHeading6"))
        self.actionStylePreformatted = QtGui.QAction(MainWindow)
        self.actionStylePreformatted.setObjectName(_fromUtf8("actionStylePreformatted"))
        self.actionStyleAddress = QtGui.QAction(MainWindow)
        self.actionStyleAddress.setObjectName(_fromUtf8("actionStyleAddress"))
        self.actionFormatFontName = QtGui.QAction(MainWindow)
        self.actionFormatFontName.setObjectName(_fromUtf8("actionFormatFontName"))
        self.actionFormatTextColor1 = QtGui.QAction(MainWindow)
        self.actionFormatTextColor1.setIcon(icon13)
        self.actionFormatTextColor1.setText(_fromUtf8(""))
        self.actionFormatTextColor1.setIconText(_fromUtf8(""))
        self.actionFormatTextColor1.setObjectName(_fromUtf8("actionFormatTextColor1"))
        self.actionFormatBackgroundColor1 = QtGui.QAction(MainWindow)
        self.actionFormatBackgroundColor1.setIcon(icon14)
        self.actionFormatBackgroundColor1.setText(_fromUtf8(""))
        self.actionFormatBackgroundColor1.setObjectName(_fromUtf8("actionFormatBackgroundColor1"))
        self.actionFormatFontSize1 = QtGui.QAction(MainWindow)
        self.actionFormatFontSize1.setIcon(icon12)
        self.actionFormatFontSize1.setText(_fromUtf8(""))
        self.actionFormatFontSize1.setObjectName(_fromUtf8("actionFormatFontSize1"))
        self.standardToolBar.addAction(self.actionSave)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionEditUndo)
        self.standardToolBar.addAction(self.actionEditRedo)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionEditCut)
        self.standardToolBar.addAction(self.actionEditCopy)
        self.standardToolBar.addAction(self.actionEditPaste)
        self.standardToolBar.addSeparator()
        self.standardToolBar.addAction(self.actionZoomOut)
        self.standardToolBar.addAction(self.actionZoomIn)
        self.formatToolBar.addAction(self.actionFormatBold)
        self.formatToolBar.addAction(self.actionFormatItalic)
        self.formatToolBar.addAction(self.actionFormatUnderline)
        self.formatToolBar.addAction(self.actionFormatStrikethrough)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionFormatFontSize)
        self.formatToolBar.addAction(self.actionFormatTextColor)
        self.formatToolBar.addAction(self.actionFormatBackgroundColor)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionFormatAlignLeft)
        self.formatToolBar.addAction(self.actionFormatAlignCenter)
        self.formatToolBar.addAction(self.actionFormatAlignRight)
        self.formatToolBar.addAction(self.actionFormatAlignJustify)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionFormatDecreaseIndent)
        self.formatToolBar.addAction(self.actionFormatIncreaseIndent)
        self.formatToolBar.addSeparator()
        self.formatToolBar.addAction(self.actionFormatNumberedList)
        self.formatToolBar.addAction(self.actionFormatBulletedList)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Client Information", None))
        self.standardToolBar.setWindowTitle(_translate("MainWindow", "Standard", None))
        self.formatToolBar.setWindowTitle(_translate("MainWindow", "Formatting", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionEditUndo.setText(_translate("MainWindow", "&Undo", None))
        self.actionEditUndo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionEditRedo.setText(_translate("MainWindow", "&Redo", None))
        self.actionEditRedo.setShortcut(_translate("MainWindow", "Ctrl+Y", None))
        self.actionEditCut.setText(_translate("MainWindow", "Cu&t", None))
        self.actionEditCut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionEditCopy.setText(_translate("MainWindow", "&Copy", None))
        self.actionEditCopy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionEditPaste.setText(_translate("MainWindow", "&Paste", None))
        self.actionEditPaste.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.actionEditSelectAll.setText(_translate("MainWindow", "Select A&ll", None))
        self.actionEditSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.actionFormatBold.setText(_translate("MainWindow", "&Bold", None))
        self.actionFormatBold.setShortcut(_translate("MainWindow", "Ctrl+B", None))
        self.actionFormatItalic.setText(_translate("MainWindow", "&Italic", None))
        self.actionFormatItalic.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.actionFormatUnderline.setText(_translate("MainWindow", "&Underline", None))
        self.actionFormatUnderline.setShortcut(_translate("MainWindow", "Ctrl+U", None))
        self.actionFormatStrikethrough.setText(_translate("MainWindow", "&Strikethrough", None))
        self.actionFormatAlignLeft.setText(_translate("MainWindow", "Align &Left", None))
        self.actionFormatAlignCenter.setText(_translate("MainWindow", "Align &Center", None))
        self.actionFormatAlignRight.setText(_translate("MainWindow", "Align &Right", None))
        self.actionFormatAlignJustify.setText(_translate("MainWindow", "Align &Justify", None))
        self.actionFormatIncreaseIndent.setText(_translate("MainWindow", "I&ncrease Indent", None))
        self.actionFormatDecreaseIndent.setText(_translate("MainWindow", "&Decrease Indent", None))
        self.actionFormatBulletedList.setText(_translate("MainWindow", "Bulle&ted List", None))
        self.actionFormatNumberedList.setText(_translate("MainWindow", "&Numbered List", None))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out", None))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionStyleParagraph.setText(_translate("MainWindow", "&Paragraph", None))
        self.actionStyleHeading1.setText(_translate("MainWindow", "Heading &1", None))
        self.actionStyleHeading2.setText(_translate("MainWindow", "Heading &2", None))
        self.actionStyleHeading3.setText(_translate("MainWindow", "Heading &3", None))
        self.actionStyleHeading4.setText(_translate("MainWindow", "Heading &4", None))
        self.actionStyleHeading5.setText(_translate("MainWindow", "Heading &5", None))
        self.actionStyleHeading6.setText(_translate("MainWindow", "Heading &6", None))
        self.actionStylePreformatted.setText(_translate("MainWindow", "Pre&formatted", None))
        self.actionStyleAddress.setText(_translate("MainWindow", "&Address", None))
        self.actionFormatFontName.setText(_translate("MainWindow", "&Font Name...", None))

from PyQt4 import QtWebKit
import htmleditor_rc
